language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t amarbelkhede/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true amarbelkhede/docker-react npm run test